### ISSUE TITLE
Can't install, debian 9.

### ISSUE THREAD

**Issue by AcFli** [toggl/thumbler#52]
Hi,

Get the following error when doing: yarn install

/usr/share/yarn/lib/cli.js:45699
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

User error?

TIA

**Comment by shantanuraj** [comment]
Are you on node `10.14.0`?

**Comment by AcFli** [comment]
Hi,

No, forgot all about that, was using 4.8.2. Upgraded to 10.15.3 and was
able to install.

Thanks,
Fredrik

Den tis 19 mars 2019 kl 09:04 skrev Shantanu Raj <notifications@github.com>:
